import type { Metadata } from 'next'
import { Rosarivo } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'

const rosarivo = Rosarivo({ subsets: ["latin"],
display: "swap",
variable: "--font-rosarivo",
weight: "400"
})

export const metadata: Metadata = {
  title: 'TranspareSer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${rosarivo.variable}`}>
        <body className="font-crushed">
          <Header />
          {children}
        </body>
    </html>
  );
}
  